[package]
name = "rust-course"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.14.0"
colored = "3.0.0"
rand = "0.9.0"
time = "0.3.37"
regex = "1.11.1"
chrono = "0.4.39"
